name: Update README Metrics.

on:
  schedule:
    - cron: '0 0 * * *'  # Executa uma vez por dia, de madrugada
  push:
    branches:
      - main  # Roda quando há um push no branch principal

jobs:
  update-stats:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get GitHub statistics (commits, PRs, issues)
        run: |
          curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/alexvarelagomes/alexvarelagomes/stats/commit_activity" \
            > commit_stats.json

          curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/alexvarelagomes/alexvarelagomes/pulls?state=all" \
            > pull_stats.json

          curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/alexvarelagomes/alexvarelagomes/issues?state=open" \
            > issue_stats.json

      - name: Update README.md with statistics
        run: |
          commits=$(jq '[.[] | .total] | add' commit_stats.json)
          prs=$(jq 'length' pull_stats.json)
          issues=$(jq 'length' issue_stats.json)

          # Atualiza o README com as novas métricas
          sed -i "s|<!-- Commits -->|Commits feitos: $commits|g" README.md
          sed -i "s|<!-- Pull Requests -->|Pull Requests: $prs|g" README.md
          sed -i "s|<!-- Issues abertas -->|Issues abertas: $issues|g" README.md

      - name: Commit and push updated README.md
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          
          # Usar o GITHUB_TOKEN do GitHub Actions para autenticação
          git remote set-url origin https://github.com/${{ github.repository }}
          git add README.md
          git commit -m "Update README with new commit stats"
          git push
